### ISSUE TITLE
TF contention (base_laser_link)

### ISSUE THREAD

**Issue by lucasb-eyer** [strands-project/scitos_common#47]
I have the following in my `roswtf`'s output:

```
ERROR TF multiple authority contention:
 * node [/sicks300] publishing transform [base_laser_link] with parent [base_link] already published by node [/robot_state_publisher]
 * node [/robot_state_publisher] publishing transform [base_laser_link] with parent [base_link] already published by node [/sicks300]
```

**Comment by cburbridge** [comment]
This is because of the mainstream s300 driver. It should have it's TF publishing disabled in the launch file: see launch file in my comment here https://github.com/strands-project/sicks300/issues/1. Better yet, completely remove it as I did in our now deleted s300 driver.

@marc-hanheide what is going on with the s300? Are we now using the upstream one?

**Comment by nilsbore** [comment]
Should be fixed by https://github.com/strands-project/scitos_robot/pull/64

**Comment by marc-hanheide** [comment]
Our fork is in sync with upstream (only our version number is higher). Thing is that the upstream repo is not released, but our fork is. I will claim responsibility for the upstream repo and ask the maintaner to transfer ownership as they don't seem to be willing to maintain it further. But for now, I have installed from the fork which is - as I said - fully in sync.

**Comment by lucasb-eyer** [comment]
Thanks, I implemented @nilsbore solution in our launchfile.
